version: "3.8"

services:

  wordpress:
    image: wordpress:latest
    ports:
      - "3030:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./docker/wordpress:/var/www/html

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    volumes:
      - ./docker/db_data:/var/lib/mysql


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/config/nginx-only-wp.conf:/etc/nginx/nginx.conf
    depends_on:
      - wordpress
